package handcraft;
// Generated Aug 7, 2022 2:29:18 PM by Hibernate Tools 4.3.1



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer id;
     private String cname;
     private String email;
     private int mobile;
     private String usern;
     private String pass;

    public Customer() {
    }

    public Customer(String cname, String email, int mobile, String usern, String pass) {
       this.cname = cname;
       this.email = email;
       this.mobile = mobile;
       this.usern = usern;
       this.pass = pass;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCname() {
        return this.cname;
    }
    
    public void setCname(String cname) {
        this.cname = cname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getMobile() {
        return this.mobile;
    }
    
    public void setMobile(int mobile) {
        this.mobile = mobile;
    }
    public String getUsern() {
        return this.usern;
    }
    
    public void setUsern(String usern) {
        this.usern = usern;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


