package handcraft;
// Generated Aug 7, 2022 2:29:18 PM by Hibernate Tools 4.3.1



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer id;
     private String productname;
     private int quentity;
     private String price;
     private int postalcode;
     private String address;
     private int mobileno;

    public Orders() {
    }

    public Orders(String productname, int quentity, String price, int postalcode, String address, int mobileno) {
       this.productname = productname;
       this.quentity = quentity;
       this.price = price;
       this.postalcode = postalcode;
       this.address = address;
       this.mobileno = mobileno;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }
    public int getQuentity() {
        return this.quentity;
    }
    
    public void setQuentity(int quentity) {
        this.quentity = quentity;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }
    public int getPostalcode() {
        return this.postalcode;
    }
    
    public void setPostalcode(int postalcode) {
        this.postalcode = postalcode;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getMobileno() {
        return this.mobileno;
    }
    
    public void setMobileno(int mobileno) {
        this.mobileno = mobileno;
    }




}


